In [6]:
import numpy as np # Import the numpy library and alias it as np

# Create a 1D array of distance run (in km) by 8 midfielders
distances = np.array(
    [8.5, 11.2, 9.8, 10.6, 7.9, 12.1, 10.0, 11.5]
)  # Convert list to array

# Create the boolean mask: condition evaluates every element
high_workrate_mask = (
    distances > 10.5
)  # Returns True if distance > 10.5, else False

# Apply the mask inside square brackets to extract matching values
elite_runners = distances[
    high_workrate_mask
]  # Selects only elements where mask is True

print("Original Distances:", distances)
print("Boolean Mask:      ", high_workrate_mask)
print("Elite Runners:     ", elite_runners)

Original Distances: [ 8.5 11.2  9.8 10.6  7.9 12.1 10.  11.5]
Boolean Mask:       [False  True False  True False  True False  True]
Elite Runners:      [11.2 10.6 12.1 11.5]


Pass 2: Multiple Conditions (Bitwise Operators)

In [7]:
# Create a multi-condition mask using bitwise & (AND)
# Both conditions must be True for the result to be True
optimal_zone = (distances > 10.0) & (
    distances < 11.8
)  # Parentheses are mandatory!

# Extract the values matching both criteria
optimal_runners = distances[optimal_zone]  # Apply mask to array

print("Optimal Zone Mask:", optimal_zone)
print("Optimal Runners:  ", optimal_runners)

Optimal Zone Mask: [False  True False  True False False False  True]
Optimal Runners:   [11.2 10.6 11.5]


Pass 3: Conditional Replacement with np.where()

In [8]:
# np.where(condition, value_if_true, value_if_false)
# If distance >= 10.5, label 'High', otherwise label 'Normal'
fitness_labels = np.where(
    distances >= 10.5, "High", "Normal"
)  # Vectorized if/else

print("Distances:     ", distances)
print("Fitness Labels:", fitness_labels)

Distances:      [ 8.5 11.2  9.8 10.6  7.9 12.1 10.  11.5]
Fitness Labels: ['Normal' 'High' 'Normal' 'High' 'Normal' 'High' 'Normal' 'High']


Pass 4: The Random Module & Reproducibility (np.random.seed)

In [9]:
# Set the random seed to guarantee reproducible results across runs
np.random.seed(
    42
)  # Seed=42 is an industry tradition, any integer works

# Generate 5 random integers between low (inclusive) and high (exclusive)
# np.random.randint(low, high, size)
simulated_goals = np.random.randint(
    0, 4, size=5
)  # Random integers from 0 up to 3

# Generate random floats from a Standard Normal Distribution (mean=0, std=1)
# np.random.randn(d0, d1, ...)
normal_noise = np.random.randn(
    5
)  # 5 samples from normal distribution

print("Simulated Goals: ", simulated_goals)
print("Normal Noise:    ", normal_noise)

Simulated Goals:  [2 3 0 2 2]
Normal Noise:     [ 0.47386083  1.36845012 -0.91682684 -0.12414718 -2.01096289]


Pass 5: Random Sampling with np.random.choice()

In [10]:
np.random.seed(42)  # Reset seed for reproducibility

squad_numbers = np.array([7, 8, 9, 10, 11, 14, 17, 20])

# np.random.choice(a, size, replace, p)
# Sample 3 random squad numbers WITHOUT replacement (no duplicates)
selected_players = np.random.choice(
    squad_numbers, size=3, replace=False
)  # Pick 3 unique items

print("Selected for testing:", selected_players)

Selected for testing: [ 8 14  7]


In [11]:
np.random.seed(10)  # Lock randomness for consistent dataset generation

# Generate squad numbers 1 to 15
players = np.arange(1, 16)  # Creates array [1, 2, ..., 15]

# Generate random match ratings between 5.0 and 9.0
# Using np.random.randint and dividing by 10 to get floats
ratings = np.random.randint(50, 91, size=15) / 10.0  # e.g., 75 -> 7.5

# Generate top sprint speeds (km/h) normally distributed around 31.0 km/h with std dev of 1.5
speeds = (
    31.0 + np.random.randn(15) * 1.5
)  # Scale standard normal to mean=31, std=1.5
speeds = np.round(speeds, 1)  # Round to 1 decimal place

print("Player IDs:     ", players)
print("Match Ratings:  ", ratings)
print("Top Speeds (km/h):", speeds)

Player IDs:      [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Match Ratings:   [5.9 8.6 6.5 5.  7.8 7.5 7.9 7.9 5.8 5.9 5.  9.  8.6 6.6 8.6]
Top Speeds (km/h): [31.  30.7 31.6 32.8 29.6 32.5 31.3 31.7 29.3 31.2 33.2 29.4 28.  28.4
 31.4]


In [12]:
# Solution 1
poor_mask = ratings < 6.0  # Create boolean mask for ratings under 6.0
underperformers = ratings[poor_mask]  # Apply mask to extract values
print("Underperformers:", underperformers)

# Solution 2
np.random.seed(99)  # Lock seed to 99 for reproducibility
dice_rolls = np.random.randint(
    1, 7, size=10
)  # low=1 (inclusive), high=7 (exclusive), size=10
print("Dice Rolls:", dice_rolls)

# Solution 3
# np.where(condition, value_if_true, value_if_false)
speed_category = np.where(
    speeds >= 31.0, "Fast", "Average"
)  # Categorize speeds
print("Speed Categories:", speed_category)

Underperformers: [5.9 5.  5.8 5.9 5. ]
Dice Rolls: [2 4 2 1 2 1 3 5 6 5]
Speed Categories: ['Fast' 'Average' 'Fast' 'Fast' 'Average' 'Fast' 'Fast' 'Fast' 'Average'
 'Fast' 'Fast' 'Average' 'Average' 'Average' 'Fast']


In [13]:
# Solution 4
# Combine conditions using bitwise & and mandatory parentheses
elite_mask = (ratings >= 7.5) & (speeds >= 30.5)
elite_player_ids = players[elite_mask]  # Index players array using the mask
print("Elite Two-Way Player IDs:", elite_player_ids)

# Solution 5
# np.where(condition, x, y): if True replace with 5.5, if False keep original rating
adjusted_ratings = np.where(ratings < 5.5, 5.5, ratings)
print("Adjusted Ratings:", adjusted_ratings)

Elite Two-Way Player IDs: [ 2  6  7  8 15]
Adjusted Ratings: [5.9 8.6 6.5 5.5 7.8 7.5 7.9 7.9 5.8 5.9 5.5 9.  8.6 6.6 8.6]


In [14]:
# Solution 6
np.random.seed(2026)  # Set reproducible seed

# np.random.choice(a, size, replace)
captain_candidates = np.random.choice(
    players, size=4, replace=False
)  # Sample 4 unique players
print("Captain Candidates:", captain_candidates)

# Bitwise OR (|) evaluates True if EITHER condition is met
extreme_ratings_mask = (ratings >= 8.0) | (ratings <= 5.5)
extreme_ratings = ratings[extreme_ratings_mask]  # Extract extreme ratings
print("Extreme Ratings:", extreme_ratings)

Captain Candidates: [14 12 15  1]
Extreme Ratings: [8.6 5.  5.  9.  8.6 8.6]


In [15]:
# --- MINI PROJECT: MATCH DAY ANALYTICS ---
import numpy as np

# 1. Initialize reproducibility
np.random.seed(77)

# 2. Simulate data for 20 players
player_ids = np.arange(1, 21)  # Players 1 to 20

# Simulate distances run (km): normal distribution centered at 10.0 km, std dev 1.2
distances_km = np.round(10.0 + np.random.randn(20) * 1.2, 1)

# Simulate match ratings from 5.0 to 10.0
match_ratings = np.random.randint(50, 101, size=20) / 10.0

print("--- RAW SQUAD DATA ---")
print("Player IDs:   ", player_ids)
print("Distances:    ", distances_km)
print("Ratings:      ", match_ratings)
print("-" * 30)

# 3. Apply Boolean Masking: Find 'Workhorse Elite' players
# Condition: Ran more than 10.5 km AND achieved rating >= 7.5
workhorse_mask = (distances_km > 10.5) & (match_ratings >= 7.5)

elite_ids = player_ids[workhorse_mask]  # Extract IDs
elite_ratings = match_ratings[workhorse_mask]  # Extract Ratings

print("--- ELITE WORKHORSE PLAYERS ---")
print("Elite Player IDs: ", elite_ids)
print("Their Ratings:    ", elite_ratings)
print("-" * 30)

# 4. Conditional Replacement: Create Performance Tiers
# If rating >= 8.0 -> 'Star', else -> 'Squad'
performance_tiers = np.where(match_ratings >= 8.0, "Star", "Squad")
print("Performance Tiers:", performance_tiers)
print("-" * 30)

# 5. Random Sampling: Select 2 unique players for mandatory post-match testing
# Must be sampled without replacement so we don't pick the same player twice
selected_for_testing = np.random.choice(player_ids, size=2, replace=False)
print("--- MANDATORY TESTING SELECTION ---")
print("Players selected for testing:", selected_for_testing)

--- RAW SQUAD DATA ---
Player IDs:    [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Distances:     [10.3 10.8  9.3 10.5 10.6  7.6 10.3  8.1 11.9  9.1 10.4 11.4  8.7  8.8
  9.2 12.   8.5  9.8  9.9  9.8]
Ratings:       [9.1 7.8 5.  7.8 9.  7.5 8.7 6.1 5.3 6.8 8.6 7.1 7.2 9.5 6.4 9.4 8.7 7.6
 6.7 8.4]
------------------------------
--- ELITE WORKHORSE PLAYERS ---
Elite Player IDs:  [ 2  5 16]
Their Ratings:     [7.8 9.  9.4]
------------------------------
Performance Tiers: ['Star' 'Squad' 'Squad' 'Squad' 'Star' 'Squad' 'Star' 'Squad' 'Squad'
 'Squad' 'Star' 'Squad' 'Squad' 'Star' 'Squad' 'Star' 'Star' 'Squad'
 'Squad' 'Star']
------------------------------
--- MANDATORY TESTING SELECTION ---
Players selected for testing: [14  2]


Question 1: Given a 1D NumPy array arr = np.array([12, -3, 0, 8, -5, 20]), write a single line of code using np.where() to replace all negative numbers with 0, leaving positive numbers and zero unchanged.

In [17]:
arr = np.array([12, -3, 0, 8, -5, 20])
new_arr = np.where(arr < 0 , 0  , arr)
print(new_arr)

[12  0  0  8  0 20]


Question 2: Write the code to generate a 1D NumPy array named sample containing exactly 5 random numbers drawn from a Standard Normal Distribution, ensuring that anyone running your code gets the exact same 5 numbers by setting a seed of 123 first.

In [18]:
import numpy as np

# Set the seed for reproducibility
np.random.seed(123)

# Generate 5 random numbers from a Standard Normal Distribution
sample = np.random.randn(5)

print(sample)


[-1.0856306   0.99734545  0.2829785  -1.50629471 -0.57860025]


Question 3: Given an array of prices prices = np.array([15.0, 45.0, 30.0, 99.0, 12.0, 60.0]), use Boolean Masking (not np.where) to extract and assign to a new variable mid_range only the prices that are >= 20.0 and <= 70.0.

In [19]:
import numpy as np

prices = np.array([15.0, 45.0, 30.0, 99.0, 12.0, 60.0])

# Create the boolean mask and extract the prices
mask = (prices >= 20.0) & (prices <= 70.0)
mid_range = prices[mask]

print(mid_range)


[45. 30. 60.]
