# Day 18 — NumPy Math Operations for Data Science

FC Lahore Lions ⚽ analytics practice: matrix multiplication, sqrt/exp/log, manual RMSE, and cosine similarity — built entirely from scratch using NumPy.

## Objective

By the end of this notebook I can:
- Use `np.dot()` for vector and matrix multiplication
- Use `np.sqrt()`, `np.exp()`, and `np.log()` for element-wise math
- Build RMSE (Root Mean Squared Error) manually, without sklearn
- Build Cosine Similarity from scratch to compare two players' stats

## Imports

In [1]:
import numpy as np

## Theory

- **`np.dot(A, B)`** — multiplies and sums vectors/matrices. Matrix × vector gives a weighted score per row. Matrix × matrix combines two matrices row-by-column.
- **`np.sqrt()`** — square root, undoes squaring. Used to bring squared errors back to real units (RMSE).
- **`np.exp()`** — e^x, explosive growth. Used in probability and gradient descent.
- **`np.log()`** — natural log, undoes `exp`. Used in log-loss and scaling.
- **RMSE** — `sqrt(mean((y_pred - y_actual)**2))` — average prediction error, in the same unit as the target.
- **Cosine Similarity** — `dot(A,B) / (magnitude(A) * magnitude(B))` — measures how similar two vectors' *directions* are, from -1 (opposite) to 1 (identical).

## Example 1 — Matrix Multiplication with `np.dot()`

In [2]:
# Each row = one player: [goals, assists, shots_on_target]
players = np.array([
    [2, 1, 5],   # Hamza
    [0, 3, 2],   # Bilal
    [1, 1, 4]    # Usman
])

# Points weight system: goal=3pts, assist=2pts, shot_on_target=1pt
weights = np.array([3, 2, 1])

# np.dot multiplies each row by the weights, then sums the result per row
performance_score = np.dot(players, weights)
print("Performance scores:", performance_score)

Performance scores: [13  8  9]


In [3]:
# Matrix x Matrix: comparing two full squads at once
lions_squad = np.array([
    [2, 1, 5],   # Hamza
    [0, 3, 2]    # Bilal
])

karachi_squad = np.array([
    [1, 0],
    [2, 1],
    [0, 3]
])

# columns of lions_squad (3) must match rows of karachi_squad (3)
matchup = np.dot(lions_squad, karachi_squad)
print("Matchup result:\n", matchup)

Matchup result:
 [[ 4 16]
 [ 6  9]]


## Example 2 — `np.sqrt()`, `np.exp()`, `np.log()`, and Manual RMSE

In [4]:
distances_squared = np.array([16, 25, 9, 4])

# sqrt undoes squaring - brings values back to real units
distances = np.sqrt(distances_squared)
print("Distances:", distances)

Distances: [4. 5. 3. 2.]


In [5]:
match_ratings = np.array([1, 2, 3])

# exp grows numbers explosively
growth = np.exp(match_ratings)
print("Growth:", growth)

# log undoes exp - brings us back to the original numbers
back_to_original = np.log(growth)
print("Back to original:", back_to_original)

Growth: [ 2.71828183  7.3890561  20.08553692]
Back to original: [1. 2. 3.]


In [6]:
# Manual RMSE - built from scratch, no sklearn needed
y_actual = np.array([2, 0, 1])       # actual goals scored
y_pred   = np.array([1.5, 0.5, 1.2])  # model's predicted goals

errors = y_pred - y_actual
squared_errors = errors ** 2
mean_squared_error = np.mean(squared_errors)
rmse = np.sqrt(mean_squared_error)

print("Errors:", errors)
print("RMSE:", rmse)

# one-liner version (same result, more compact)
rmse_oneliner = np.sqrt(np.mean((y_pred - y_actual) ** 2))
print("RMSE (one-liner):", rmse_oneliner)

Errors: [-0.5  0.5  0.2]
RMSE: 0.42426406871192857
RMSE (one-liner): 0.42426406871192857


In [7]:
# Cosine Similarity - built from scratch using dot product + magnitude
hamza = np.array([2, 1, 5])   # goals, assists, shots
bilal = np.array([0, 3, 2])

dot_product = np.dot(hamza, bilal)
magnitude_hamza = np.sqrt(np.sum(hamza ** 2))
magnitude_bilal = np.sqrt(np.sum(bilal ** 2))

cosine_similarity = dot_product / (magnitude_hamza * magnitude_bilal)
print("Cosine Similarity:", cosine_similarity)
# 0.658 -> moderately similar playing style (1 = identical, 0 = unrelated, -1 = opposite)

Cosine Similarity: 0.6582805886043833


## Practice Exercise — 12 Coding Challenges (Beginner → Advanced)

All solved using only today's concepts: `np.dot`, `np.sqrt`/`exp`/`log`, manual RMSE, and cosine similarity.

**Beginner 1** — Square roots of `[4, 9, 16, 25]`

In [8]:
arr = np.array([4, 9, 16, 25])
print(np.sqrt(arr))

[2. 3. 4. 5.]


**Beginner 2** — Dot product of two length-3 arrays

In [9]:
shafi = np.array([1, 2, 3])
shafay = np.array([4, 5, 6])
print(np.dot(shafi, shafay))

32


**Beginner 3** — `np.exp()` of `[0, 1, 2]`

In [10]:
values = np.array([0, 1, 2])
print(np.exp(values))

[1.         2.71828183 7.3890561 ]


**Beginner 4** — `np.log()` of `[1, 10, 100]`

In [11]:
values = np.array([1, 10, 100])
print(np.log(values))

[0.         2.30258509 4.60517019]


**Beginner 5** — Square `[2, -3, 4]` and find the mean

In [12]:
errors = np.array([2, -3, 4])
squared_errors = errors ** 2
mean_squared = np.mean(squared_errors)
print(mean_squared)

9.666666666666666


**Intermediate 6** — RMSE as a reusable function

In [13]:
def rmse(y_pred, y_actual):
    errors = y_pred - y_actual
    squared_errors = errors ** 2
    mean_squared_error = np.mean(squared_errors)
    return np.sqrt(mean_squared_error)

# test it
test_actual = np.array([1, 2, 3])
test_pred = np.array([4, 5, 6])
print("RMSE:", rmse(test_pred, test_actual))

RMSE: 3.0


**Intermediate 7** — Matrix × matrix with `np.dot()`

In [14]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(np.dot(A, B))

[[19 22]
 [43 50]]


**Intermediate 8** — `magnitude(v)` function

In [15]:
def magnitude(v):
    return np.sqrt(np.sum(v ** 2))

test_vector = np.array([3, 4])
print("Magnitude:", magnitude(test_vector))  # classic 3-4-5 triangle -> 5.0

Magnitude: 5.0


**Intermediate 9** — Confirm `np.log(np.exp(5))` equals `5`

In [16]:
result = np.log(np.exp(5))
print(result)  # 5.0 -> log and exp undo each other

5.0


**Advanced 10** — `cosine_similarity(v1, v2)` function, tested on two players

In [17]:
def cosine_similarity(v1, v2):
    dot_product = np.dot(v1, v2)
    mag1 = magnitude(v1)
    mag2 = magnitude(v2)
    return dot_product / (mag1 * mag2)

aliyan = np.array([1, 2, 3])
haseeb = np.array([4, 5, 6])
print("Similarity:", cosine_similarity(aliyan, haseeb))

Similarity: 0.9746318461970762


**Advanced 11** — Compare two prediction arrays against the same `y_actual` using `rmse()`

In [18]:
actual = np.array([1, 2, 3])
pred_a = np.array([1.1, 2.2, 2.9])
pred_b = np.array([2.0, 3.5, 1.0])

rmse_a = rmse(pred_a, actual)
rmse_b = rmse(pred_b, actual)

print("Model A RMSE:", rmse_a)
print("Model B RMSE:", rmse_b)
print("More accurate model:", "A" if rmse_a < rmse_b else "B")

Model A RMSE: 0.14142135623730964
Model B RMSE: 1.5545631755148024
More accurate model: A


**Advanced 12** — 3x3 squad stats matrix, weighted scores, and the top player with `np.max()`

In [19]:
squad_stats = np.array([
    [85, 90, 88],  # Player 1
    [92, 85, 95],  # Player 2
    [88, 92, 80]   # Player 3
])

weights = np.array([0.4, 0.4, 0.2])

scores = np.dot(squad_stats, weights)
print("Scores:", scores)
print("Highest score:", np.max(scores))
print("Top player index:", np.argmax(scores))

Scores: [87.6 89.8 88. ]
Highest score: 89.8
Top player index: 1


## Mini Challenge — "Lions Scout Report"

Full mini-project using only today's Ledger: performance scoring, similarity matching, and RMSE evaluation.

In [20]:
# 1. Stats matrix for 4 players: goals, assists, shots, passes
player_names = ["Hamza", "Bilal", "Ahmed", "Ali"]

hamza = np.array([8, 5, 30, 120])
bilal = np.array([6, 7, 25, 140])
ahmed = np.array([10, 3, 40, 100])
ali   = np.array([4, 9, 20, 160])

squad = np.array([hamza, bilal, ahmed, ali])

# 2. Weighted performance score
weights = np.array([0.4, 0.3, 0.2, 0.1])
scores = np.dot(squad, weights)

for name, score in zip(player_names, scores):
    print(f"{name}: {score:.2f}")

top_player_index = np.argmax(scores)
print("\nTop performer:", player_names[top_player_index])

Hamza: 22.70
Bilal: 23.50
Ahmed: 22.90
Ali: 24.30

Top performer: Ali


In [21]:
# 3. Cosine similarity between the star player and every other player
star_index = top_player_index
star_player = squad[star_index]

print(f"Comparing everyone to {player_names[star_index]}:\n")

best_match_index = None
best_match_score = -2  # cosine similarity ranges from -1 to 1

for i, name in enumerate(player_names):
    if i == star_index:
        continue
    sim = cosine_similarity(star_player, squad[i])
    print(f"{player_names[star_index]} vs {name}: {sim:.4f}")
    if sim > best_match_score:
        best_match_score = sim
        best_match_index = i

print(f"\nMost similar playing style to {player_names[star_index]}: {player_names[best_match_index]}")

Comparing everyone to Ali:

Ali vs Hamza: 0.9919
Ali vs Bilal: 0.9985
Ali vs Ahmed: 0.9649

Most similar playing style to Ali: Bilal


In [22]:
# 4. Simulate predictions and compute RMSE
actual_goals = np.array([8, 6, 10, 4])
predicted_goals = np.array([7, 6, 9, 5])

model_rmse = rmse(predicted_goals, actual_goals)
print("Predicted vs actual goals RMSE:", round(model_rmse, 3))

Predicted vs actual goals RMSE: 0.866


In [23]:
# 5. Scout summary
print("=== LIONS SCOUT REPORT ===")
print(f"Top performer: {player_names[top_player_index]} (score: {scores[top_player_index]:.2f})")
print(f"Most similar pair: {player_names[star_index]} & {player_names[best_match_index]} (similarity: {best_match_score:.4f})")
print(f"Prediction model RMSE: {model_rmse:.3f} goals")

=== LIONS SCOUT REPORT ===
Top performer: Ali (score: 24.30)
Most similar pair: Ali & Bilal (similarity: 0.9985)
Prediction model RMSE: 0.866 goals


## Summary

- `np.dot()` handles vector and matrix multiplication — the same operation used inside every neural network layer.
- `np.sqrt()`, `np.exp()`, `np.log()` are element-wise math tools — no loops needed.
- RMSE = `sqrt(mean((pred - actual)**2))` — the standard way to report regression error, in real units.
- Cosine Similarity = `dot(A,B) / (magnitude(A) * magnitude(B))` — the same math behind Netflix/Spotify recommendations.
- Practiced everything on the FC Lahore Lions dataset — performance scoring, player similarity matching, and prediction evaluation.

**Next up:** Day 19 — Boolean Masking & Random Module.