In [13]:
import numpy as np

goals = np.array([2, 1, 0, 3, 1])   # Ali, Zeeshan, Bilal, Hamza, Usman
points = goals * 3                   # 3 league points per goal (hypothetical bonus system)
print(points)

[6 3 0 9 3]


In [14]:
assists = np.array([1, 2, 0, 1, 0])
total_contributions = goals + assists
print(total_contributions)

[3 3 0 4 1]


In [15]:
weighted_score = (goals * 4) + (assists * 2)
print(weighted_score)

[10  8  0 14  4]


 Broadcasting

In [16]:
goals_matrix = np.array([
    [2, 1, 0, 3, 1],   # Match 1
    [1, 0, 2, 1, 0],   # Match 2
    [3, 2, 1, 0, 2],   # Match 3
    [0, 1, 1, 2, 1]    # Match 4
])
print(goals_matrix.shape)

(4, 5)


Add a flat home-advantage bonus of 1 goal to every single value:


In [17]:
boosted = goals_matrix + 1
print(boosted)

[[3 2 1 4 2]
 [2 1 3 2 1]
 [4 3 2 1 3]
 [1 2 2 3 2]]


In [18]:
player_bonus = np.array([0, 1, 0, 0, 1])   # Zeeshan and Usman get +1 (man-of-match streak)
print(goals_matrix.shape, player_bonus.shape)

boosted_matrix = goals_matrix + player_bonus
print(boosted_matrix)

(4, 5) (5,)
[[2 2 0 3 2]
 [1 1 2 1 1]
 [3 3 1 0 3]
 [0 2 1 2 2]]


axis-based aggregation (sum, mean, max with axis)

In [19]:
total_per_player = goals_matrix.sum(axis=0)
print(total_per_player)

[6 4 4 6 4]


In [20]:
total_per_match = goals_matrix.sum(axis=1)
print(total_per_match)

[7 4 8 5]


In [21]:
avg_goals_per_player = goals_matrix.mean(axis=0)
print(avg_goals_per_player)

best_match_score = goals_matrix.max(axis=1)
print(best_match_score)

[1.5 1.  1.  1.5 1. ]
[3 2 3 2]


 Reshape & Transpose

In [22]:
shots = np.arange(20)
print(shots)

shots_grid = shots.reshape(4, 5)
print(shots_grid)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [23]:
goals_column = goals.reshape(-1, 1)
print(goals_column)
print(goals_column.shape)

[[2]
 [1]
 [0]
 [3]
 [1]]
(5, 1)


In [24]:
print(goals_matrix.shape)
flipped = goals_matrix.T
print(flipped.shape)
print(flipped)

(4, 5)
(5, 4)
[[2 1 3 0]
 [1 0 2 1]
 [0 2 1 1]
 [3 1 0 2]
 [1 0 2 1]]


In [27]:
# Q1 — Fix the error
a = np.array([1, 2, 3, 4])
b = np.array([1, 2, 3, 4])
c = a + b
print(c)

[2 4 6 8]


In [29]:
# Q2 — This runs but gives the WRONG axis. Fix it so you get
# total goals PER MATCH (one number per row), not per player.
totals = goals_matrix.sum(axis=1)
print(totals)

[7 4 8 5]


In [37]:
# Q3 — Fix the reshape error
x = np.arange(10)
y = x.reshape(5,2 )
print(y)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [41]:
# Q4 — Fix the indentation/logic: this should add player_bonus
# to goals_matrix but crashes
bonus = np.array([1, 0, 1, 0, 1])
result = goals_matrix + bonus
print(result)

[[3 1 1 3 2]
 [2 0 3 1 1]
 [4 2 2 0 3]
 [1 1 2 2 2]]


In [43]:
# Q5 — Find the bug: goal is to get a column vector of shape (5,1)
col = goals.reshape(-1,1)
print(col.shape)

(5, 1)


# 1. Create arr = np.array([5, 10, 15, 20]). Multiply every element by 2. Print result.

# 2. Create two arrays: home = np.array([2,1,3]), away = np.array([1,0,2]).
# Add them element-wise to get total goals per match. Print result.

# 3. Given scores = np.array([10, 20, 30, 40, 50, 60]), reshape it into a 2x3 grid. Print it.

# 4. Given prices = np.array([100, 200, 300]), reshape it into a column vector (3,1). Print shape.

# 5. Create a (3,4) array of your choice. Print its transpose and the transpose's shape.

In [44]:
arr = np.array([5, 10, 15, 20])
print(arr * 2)

[10 20 30 40]


In [45]:
home = np.array([2,1,3])
away = np.array([1,0,2])
total_goal_per_match = home + away
print(total_goal_per_match)

[3 1 5]


In [47]:
scores = np.array([10, 20, 30, 40, 50, 60])
reshaped_scores = scores.reshape(2,3)
print(reshaped_scores)
print(reshaped_scores.shape)

[[10 20 30]
 [40 50 60]]
(2, 3)


In [49]:
prices = np.array([100, 200, 300])
reshaped_prices = prices.reshape(-1,1)
print(reshaped_prices.shape)
print(reshaped_prices)

(3, 1)
[[100]
 [200]
 [300]]


In [52]:
shafi = np.array([[1,1,1,1],
                  [1,1,1,1],
                  [1,1,1,1]
                  ])
print(shafi.shape)
transpose_shafi = shafi.T
print(transpose_shafi.shape)
print(transpose_shafi)

(3, 4)
(4, 3)
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]


# 6. matches = np.array([[3,1,2],[0,2,1],[1,1,3]])  # 3 matches x 3 players
# Find total goals per player (across all matches) using axis.

# 7. Using the same 'matches' array, find total goals per match using axis.

# 8. Add a flat bonus of 2 to every value in 'matches' using broadcasting. Print result.

# 9. Create player_bonus = np.array([1,0,2]) and add it to 'matches' using broadcasting.
# Explain in one line (as a comment) why this works shape-wise.

# 10. Find the average goals per match (axis-based mean) for 'matches'.

In [55]:
matches = np.array([[3,1,2],
                    [0,2,1],
                     [1,1,3]])
goals_per_player = matches.sum(axis=0)
print(goals_per_player)

[4 4 6]


In [54]:
goals_per_match = matches.sum(axis=1)
print(goals_per_match)

[6 3 5]


In [56]:
bonus_goals = matches + 2
print(bonus_goals)

[[5 3 4]
 [2 4 3]
 [3 3 5]]


In [58]:
player_bonus = np.array([1,0,2])
matches_players = matches + player_bonus
print(matches_players)    # this works shape wise because there total of (3,3) shape so when player_bonus used the number of coloumns matches the (3,3) shape

(3, 3)


In [59]:
matches_goal_per_match = matches.mean(axis=0)
print(matches_goal_per_match)

[1.33333333 1.33333333 2.        ]


# 11. Create a (4,6) array using np.arange(24).reshape(...). Then reshape it again into (6,4)
# without recreating the original array — using only the existing variable.

# 12. matches = np.array([[3,1,2],[0,2,1],[1,1,3]])
# Find the single match (row) with the highest total goals.
# (Hint: sum with axis, then use the result to find the max — no loops.)

# 13. Take 'matches', transpose it, then find the total goals per player using the
# transposed array with the OTHER axis than you used in Q6. Confirm you get the same numbers.

In [64]:
new_arr = np.arange(24).reshape(4,6)
print(new_arr.shape)
reshape_new_arr = new_arr.reshape(6,4)
print(reshape_new_arr.shape)
print(reshape_new_arr)


(4, 6)
(6, 4)
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [66]:
new_matches = np.array([[3,1,2],
                        [0,2,1],
                         [1,1,3]
                        ])
new_matches_highest_goals = new_matches.sum(axis=1)
print(new_matches_highest_goals)
max_highest_goals = new_matches_highest_goals.max()
print(max_highest_goals)

[6 3 5]
6


In [68]:
new_matches = np.array([[3,1,2],
                        [0,2,1],
                         [1,1,3]
                        ])
transpose_new_matches = new_matches.T
print(transpose_new_matches)
new_matches_goalsperplayer = new_matches.sum(axis=1)
print(new_matches_goalsperplayer)   # it has the same answer as the Q6

[[3 0 1]
 [1 2 1]
 [2 1 3]]
[6 3 5]
