In [1]:
import numpy as np

# Python list: goals scored by 5 Lions players this season
goals_list = [5, 8, 2, 12, 6]

# NumPy array: same data, different container
goals_array = np.array(goals_list)

print(goals_list)
print(goals_array)

[5, 8, 2, 12, 6]
[ 5  8  2 12  6]


TRYING TO DOUBLE IN BOTH PYTHON LIST AND NUMPY WAY

In [2]:
Double_list = [g * 2 for g in goals_list]
Double_array = goals_array * 2

print(Double_list)
print(Double_array)

[10, 16, 4, 24, 12]
[10 16  4 24 12]


In [3]:
# 3 players x 3 matches: goals per match
lions_goals = np.array([
    [1, 0, 2],   # Player A
    [0, 1, 1],   # Player B
    [2, 2, 0]    # Player C
])
print(lions_goals)

[[1 0 2]
 [0 1 1]
 [2 2 0]]


Array creation shortcuts — np.zeros(), np.ones(), np.arange(), np.linspace()

In [4]:
new_signings = np.zeros(5)
print(new_signings)

[0. 0. 0. 0. 0.]


In [5]:
fit_flags = np.ones(5)
print(fit_flags)

[1. 1. 1. 1. 1.]


In [6]:
match_weeks = np.arange(1,11)
print(match_weeks)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
fitness_checkpoints = np.linspace(0,90,5)
print(fitness_checkpoints)

[ 0.  22.5 45.  67.5 90. ]


 Array attributes — .shape, .ndim, .dtype, .size

In [8]:
lions_goals = np.array([
    [1, 0, 2],
    [0, 1, 1],
    [2, 2, 0]
])

print(lions_goals.shape)
print(lions_goals.ndim)
print(lions_goals.dtype)
print(lions_goals.size)

(3, 3)
2
int64
9


SIZE VS SHAPE DIFFERENCE

In [9]:
salaries = np.array([50000.5, 62000.75, 48000.0])
print(salaries.dtype)   # float64, because of the decimals
print(salaries.shape)
print(salaries.size)   # (3,) - a 1D array of 3 values

float64
(3,)
3


 Indexing and slicing (1D and 2D)

In [11]:
goals_array = np.array([5, 8, 2, 12, 6])

print(goals_array[0])      # first player's goals
print(goals_array[1:4])    # players 2 to 4 (index 1,2,3)
print(goals_array[-1])     # last player's goals

5
[ 8  2 12]
6


In [12]:
lions_goals = np.array([
    [1, 0, 2],   # Player A
    [0, 1, 1],   # Player B
    [2, 2, 0]    # Player C
])

print(lions_goals[0, 2])    # Player A, match 3 → single value
print(lions_goals[:, 1])    # everyone's goals in match 2 → a column
print(lions_goals[1, :])    # Player B's goals in all matches → a row

2
[0 1 2]
[0 1 1]


In [15]:
players = np.array([3, 7, 9, 5])
print(players)

[3 7 9 5]


In [17]:
match_weeks = np.arange(1, 11)
# Shafi expected 10 match weeks (1 through 10) but got 9
print(match_weeks)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
lions_goals = np.array([[1,0,2],
                       [0,1,1],
                       [2,2,0]])
# Trying to get Player B's (row index 1) goals in all matches
print(lions_goals[1,: ])

[0 1 1]


Create a 1D array attendance from the list [45000, 38000, 52000, 41000] (fans per match).

In [21]:
attendance_arr = np.array([45000, 38000, 52000, 41000])
print(attendance_arr)

[45000 38000 52000 41000]


Print attendance[2] — the 3rd match's attendance.


In [22]:
print(attendance_arr[2])

52000


Create a np.zeros(6) array called bench_minutes for 6 substitute players.


In [23]:
bench_minutes = np.zeros(6)
print(bench_minutes)

[0. 0. 0. 0. 0. 0.]


Create match_days = np.arange(1, 6) for a 5-match week — print it and confirm it shows 1 to 5.

In [24]:
match_days = np.arange(1,6)
print(match_days)

[1 2 3 4 5]


Print attendance.shape and attendance.size — explain in one sentence what each number means.

In [25]:
print(attendance_arr.shape)   # tells us the number of rows and coloumns
print(attendance_arr.size)    # tells us the total number of coloumns and rows combined

(4,)
4


Slice attendance[1:3] — which two matches does this give you?


In [26]:
print(attendance_arr[1:3])   # [38000 52000]

[38000 52000]


Create fitness_scale = np.linspace(0, 100, 5) — five evenly spaced fitness levels from 0 to 100.

In [28]:
fitness_scale = np.linspace(0,100,5)
print(fitness_scale)

[  0.  25.  50.  75. 100.]


Print attendance.dtype — is it int or float? Why?



In [29]:
print(attendance_arr.dtype)  # int becuase there are no decimals inside it

int64


9. Create a 2D array player_stats with 4 players × 3 stats (goals, assists, yellow cards):


In [30]:
player_stats = np.array([[3, 2, 1],
 [5, 1, 0],
 [0, 4, 2],
 [2, 2, 1]])

print(player_stats)

[[3 2 1]
 [5 1 0]
 [0 4 2]
 [2 2 1]]


In [31]:
print(player_stats.shape)
print(player_stats.ndim)

(4, 3)
2


From player_stats, extract all players' yellow card counts (column 2) using a single slice.

In [32]:
print(player_stats[:,2])

[1 0 2 1]


From player_stats, extract Player 3's full stat row (index 2) using a single slice.

In [33]:
print(player_stats[2,:])

[0 4 2]


Print player_stats[3, 0] — whose goal count is this, and what value do you expect before running it?

In [34]:
print(player_stats[3,0])  # obvoius player 4 goal count

2


Create home_goals = np.array([2, 1, 3, 0, 2]) and away_goals as a Python list [10, 20, 30, 40, 50] (not converted). Multiply home_goals * 2 and try away_goals * 2 — describe the difference in behavior and explain why using what you learned about arrays vs lists.

In [36]:
home_goals = np.array([2, 1, 3, 0, 2])
python_list =  [10, 20, 30, 40, 50]

numpy_goals = home_goals * 2
python_goals = [pg * 2 for pg in python_list]

print(numpy_goals)
print(python_goals)

[4 2 6 0 4]
[20, 40, 60, 80, 100]


Given season_grid = np.arange(1, 13), is it possible to reshape it in your head into a .shape of (3, 4) (3 rows, 4 cols)? Just describe what values would land in row 0 vs row 1 — no code needed, since reshape isn't on today's Ledger yet.

In [ ]:
#  row 0 = [1,2,3,4]
# row 1 = [5,6,7,8]

Using only indexing/slicing (no loops), extract the diagonal-ish values player_stats[0,0], player_stats[1,1], player_stats[2,2] one at a time and add them together manually into a variable total.

In [37]:
player_variable_total = player_stats[0,0] + player_stats[1,1] + player_stats[2,2]
print(player_variable_total)

6


Step 9 — Mini Project ⚽


Create a 2D array week_stats for 5 players × 4 stats (goals, assists, shots, tackles) — make up realistic numbers.
Print .shape and .ndim to confirm your grid.
Extract and print the assists column for all players (single slice).
Extract and print Player 4's full stat row (single slice).
Create a 1D array bonus_pool = np.linspace(0, 5000, 5) representing 5 bonus tiers.
Print the goal count of the last player using negative indexing.

In [39]:
week_stats = np.array([[2,2,6,5],
                      [4,4,8,0],
                      [6,6,10,3],
                      [2,0,3,5],
                      [3,3,12,5]
                      ])

print(week_stats)

[[ 2  2  6  5]
 [ 4  4  8  0]
 [ 6  6 10  3]
 [ 2  0  3  5]
 [ 3  3 12  5]]


In [40]:
print(week_stats.shape)
print(week_stats.ndim)

(5, 4)
2


In [41]:
print(week_stats[:,1])

[2 4 6 0 3]


In [42]:
bonus_pool = np.linspace(0, 5000, 5)
print(bonus_pool)

[   0. 1250. 2500. 3750. 5000.]


Print the goal count of the last player using negative indexing.



In [50]:
print(week_stats[-1,0])

3


Given arr = np.array([1,2,3,4,5]), write code to get every element except the first and last using slicing.

In [52]:
arr = np.array([1,2,3,4,5])
print(arr[1:4])

[2 3 4]


Given a 2D array data with shape (4, 5), write code to print the last row without hardcoding the row number.

In [54]:
Two_arr = np.array([[2,2,6,5,7],
                      [4,4,8,0,4],
                      [6,6,10,3,5],
                      [2,0,3,5,3]
                      ])
print(Two_arr)

[[ 2  2  6  5  7]
 [ 4  4  8  0  4]
 [ 6  6 10  3  5]
 [ 2  0  3  5  3]]


In [56]:
print(Two_arr[-1])

[2 0 3 5 3]


Explain with code why np.array([1,2,3]) * 2 and [1,2,3] * 2 give different results.



In [57]:
numpy = np.array([1,2,3])
print(numpy * 2)      # numpy actually does mathematical computing and each element get multipied by 2

[2 4 6]


In [58]:
python = [1,2,3]
print(python * 2)   # python just muliplies it twice rather than giving answer of each element

[1, 2, 3, 1, 2, 3]


Easy: Create a 1D array of 6 match scores, print .shape, .size, .dtype.


In [59]:
ONED_arr = np.array([2,3,4,1,5,4])
print(ONED_arr.shape)
print(ONED_arr.size)
print(ONED_arr.dtype)

(6,)
6
int64


Medium: Create a 2D array (3×3) of shot-attempts data, extract the middle row AND middle column separately.

In [62]:
create_2d_arr = np.array([[1,2,3],
                          [4,5,6],
                          [7,8,9]])
print(create_2d_arr[1,:])
print(create_2d_arr[:,1])

[4 5 6]
[2 5 8]


Hard: Create np.arange(1, 21), then using only indexing/slicing (no loops), print just the values at index 0, 5, 10, 15 — one at a time, and sum them into a variable.



In [72]:
arrange = np.arange(1,21)
print(arrange)
print(arrange[0])
print(arrange[5])
print(arrange[10])
print(arrange[15])

sum = arrange[0] + arrange[5] + arrange[10] + arrange[15]
print(sum)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
1
6
11
16
34
